2024-05-10 00:07:12,153 INFO    Thread-13 :3699887 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-05-10 00:07:12,153 INFO    Thread-13 :3699887 [wandb_setup.py:_flush():76] Configure stats pid to 3699887
2024-05-10 00:07:12,153 INFO    Thread-13 :3699887 [wandb_setup.py:_flush():76] Loading settings from /home/vb2386/.config/wandb/settings
2024-05-10 00:07:12,153 INFO    Thread-13 :3699887 [wandb_setup.py:_flush():76] Loading settings from /scratch/vb2386/Documents/nerf-pytorch/wandb/settings
2024-05-10 00:07:12,153 INFO    Thread-13 :3699887 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'Sweep_Nerf', 'entity': 'vb2386', 'root_dir': '/scratch/vb2386/Documents/nerf-pytorch', 'run_id': 'dn51k4e0', 'sweep_param_path': '/scratch/vb2386/Documents/nerf-pytorch/wandb/sweep-rzd62ajv/config-dn51k4e0.yaml', 'sweep_id': 'rzd62ajv'}
2024-05-10 00:07:12,153 INFO    Thread-13 :3699887 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-10 00:07:12,153 INFO    Thread-13 :3699887 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'nerf-pytorch/profile_nerf.py', 'program_abspath': '/scratch/vb2386/Documents/nerf-pytorch/profile_nerf.py', 'program': 'profile_nerf.py'}
2024-05-10 00:07:12,153 INFO    Thread-13 :3699887 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-10 00:07:12,153 INFO    Thread-13 :3699887 [wandb_init.py:_log_setup():521] Logging user logs to /scratch/vb2386/Documents/nerf-pytorch/wandb/run-20240510_000712-dn51k4e0/logs/debug.log
2024-05-10 00:07:12,153 INFO    Thread-13 :3699887 [wandb_init.py:_log_setup():522] Logging internal logs to /scratch/vb2386/Documents/nerf-pytorch/wandb/run-20240510_000712-dn51k4e0/logs/debug-internal.log
2024-05-10 00:07:12,153 INFO    Thread-13 :3699887 [wandb_init.py:init():561] calling init triggers
2024-05-10 00:07:12,153 INFO    Thread-13 :3699887 [wandb_init.py:init():568] wandb.init called with sweep_config: {'batch_size': 2048, 'chunk': 16384, 'lrate': 0.01}
config: {}
2024-05-10 00:07:12,153 INFO    Thread-13 :3699887 [wandb_init.py:init():611] starting backend
2024-05-10 00:07:12,153 INFO    Thread-13 :3699887 [wandb_init.py:init():615] setting up manager
2024-05-10 00:07:12,158 INFO    Thread-13 :3699887 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-05-10 00:07:12,158 INFO    Thread-13 :3699887 [wandb_init.py:init():623] backend started and connected
2024-05-10 00:07:12,165 INFO    Thread-13 :3699887 [wandb_run.py:_config_callback():1347] config_cb None None {'batch_size': 2048, 'chunk': 16384, 'lrate': 0.01}
2024-05-10 00:07:12,167 INFO    Thread-13 :3699887 [wandb_init.py:init():715] updated telemetry
2024-05-10 00:07:12,168 INFO    Thread-13 :3699887 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-05-10 00:07:12,447 INFO    Thread-13 :3699887 [wandb_run.py:_on_init():2357] communicating current version
2024-05-10 00:07:12,478 INFO    Thread-13 :3699887 [wandb_run.py:_on_init():2366] got version response upgrade_message: "wandb version 0.17.0 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-05-10 00:07:12,478 INFO    Thread-13 :3699887 [wandb_init.py:init():799] starting run threads in backend
2024-05-10 00:07:12,776 INFO    Thread-13 :3699887 [wandb_run.py:_console_start():2335] atexit reg
2024-05-10 00:07:12,776 INFO    Thread-13 :3699887 [wandb_run.py:_redirect():2190] redirect: wrap_raw
2024-05-10 00:07:12,776 INFO    Thread-13 :3699887 [wandb_run.py:_redirect():2255] Wrapping output streams.
2024-05-10 00:07:12,776 INFO    Thread-13 :3699887 [wandb_run.py:_redirect():2280] Redirects installed.
2024-05-10 00:07:12,777 INFO    Thread-13 :3699887 [wandb_init.py:init():842] run started, returning control to user process
2024-05-10 00:24:21,531 ERROR   Thread-3  :3699887 [internal_api.py:execute():373] 502 response executing GraphQL.
2024-05-10 00:24:21,555 ERROR   Thread-3  :3699887 [internal_api.py:execute():374] 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>

2024-05-10 00:26:38,717 ERROR   Thread-3  :3699887 [internal_api.py:execute():373] 502 response executing GraphQL.
2024-05-10 00:26:38,718 ERROR   Thread-3  :3699887 [internal_api.py:execute():374] 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>

2024-05-10 00:59:30,071 INFO    Thread-13 :3699887 [wandb_run.py:_finish():2064] finishing run vb2386/Sweep_Nerf/dn51k4e0
2024-05-10 00:59:30,093 INFO    Thread-13 :3699887 [wandb_run.py:_atexit_cleanup():2304] got exitcode: 0
2024-05-10 00:59:30,093 INFO    Thread-13 :3699887 [wandb_run.py:_restore():2287] restore
2024-05-10 00:59:30,093 INFO    Thread-13 :3699887 [wandb_run.py:_restore():2293] restore done
2024-05-10 00:59:34,746 INFO    Thread-13 :3699887 [wandb_run.py:_footer_history_summary_info():3936] rendering history
2024-05-10 00:59:34,747 INFO    Thread-13 :3699887 [wandb_run.py:_footer_history_summary_info():3968] rendering summary
2024-05-10 00:59:34,752 INFO    Thread-13 :3699887 [wandb_run.py:_footer_sync_info():3895] logging synced files
