
Training STarted!!!!!!!!!!
Loaded blender (138, 400, 400, 4) torch.Size([40, 4, 4]) [400, 400, 555.5555155968841] ./data/nerf_synthetic/lego
Not ndc!
Begin
TRAIN views are [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
TEST views are [113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130
 131 132 133 134 135 136 137]
VAL views are [100 101 102 103 104 105 106 107 108 109 110 111 112]
[Config] Center cropping of size 200 x 200 is enabled until iter 500
blender_paper_lego 5 [9.362851] 0.3958345 4
iter time 0.15136
test poses shape torch.Size([25, 4, 4])
0 9.703636169433594e-05
1 10.976108312606812
2 11.056633472442627
3 11.112338304519653
4 11.091192245483398
5 11.127716779708862
6 11.13562560081482
7 11.106996297836304
8 11.123124837875366
9 11.089589595794678
10 11.064449310302734
11 11.074300765991211
12 11.07599687576294
13 11.06373119354248
14 11.041362524032593
15 11.061325788497925

16 11.06767225265503
17 11.052240371704102
18 11.071327209472656
19 11.111604452133179
20 11.099894523620605
21 11.145983695983887
22 11.11911416053772
23 11.092681884765625
24 11.129472255706787
Saved test set
blender_paper_lego 10 [9.681105] 0.43693525 9
iter time 0.15264
[34m[1mwandb[39m[22m: Ctrl + C detected. Stopping sweep.
Traceback (most recent call last):
  File "profile_nerf.py", line 552, in run
    train(args)
  File "profile_nerf.py", line 887, in train
    rgb, disp, acc, extras = render(H, W, K, chunk=args.chunk, c2w=pose, **render_kwargs_test)
  File "profile_nerf.py", line 127, in render
    all_ret = batchify_rays(rays, chunk, **kwargs)
  File "profile_nerf.py", line 60, in batchify_rays
    ret = render_rays(rays_flat[i:i+chunk], **kwargs)
  File "profile_nerf.py", line 402, in render_rays
    raw = network_query_fn(pts, viewdirs, run_fn)
  File "profile_nerf.py", line 202, in <lambda>
    network_query_fn = lambda inputs, viewdirs, network_fn : run_network(inputs, viewdirs, network_fn,
  File "profile_nerf.py", line 50, in run_network
    outputs_flat = batchify(fn, netchunk)(embedded)
  File "profile_nerf.py", line 34, in ret
    return torch.cat([fn(inputs[i:i+chunk]) for i in range(0, inputs.shape[0], chunk)], 0)
  File "profile_nerf.py", line 34, in <listcomp>
    return torch.cat([fn(inputs[i:i+chunk]) for i in range(0, inputs.shape[0], chunk)], 0)
  File "/scratch/vb2386/Documents/nerf-pytorch/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/scratch/vb2386/Documents/nerf-pytorch/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/vb2386/Documents/nerf-pytorch/run_nerf_helpers.py", line 101, in forward
    h = F.relu(h)
  File "/scratch/vb2386/Documents/nerf-pytorch/venv/lib/python3.8/site-packages/torch/nn/functional.py", line 1473, in relu
    result = torch.relu(input)
Exception